## Junction Tree Algorithm

In [2]:
# import essential package
# THIS CODE NEED TO RUN IN PYTHON 3.X
import numpy as np


In [80]:
# current potential of cliques
potential_12 = np.array([[0.1, 0.7], [0.8, 0.3]])
potential_23 = np.array([[0.5, 0.1], [0.1, 0.5]])
potential_34 = np.array([[0.1, 0.5], [0.5, 0.1]])
potential_45 = np.array([[0.9, 0.3], [0.1, 0.3]])

ini_seperator = np.array([1., 1.])
# randomlt select one node as root
# root:clique x4x5
# initialization
cliques = {
    1:potential_12,
    2:potential_23,
    3:potential_34,
    4:potential_45
}

seperator = {
    2:ini_seperator,
    3:ini_seperator,
    4:ini_seperator
}
# collect and distribute 
print('initialize:--------')
print(cliques)

# collect stage
# update seperator and clique potential
def collect(previous_clique, current_clique):
    old_seperator = np.array([1., 1.])
    old_clique = current_clique
    new_seperator = np.sum(previous_clique, axis=0)
    new_clique = np.row_stack(((new_seperator / old_seperator)[0] * old_clique[0, :],
                               (new_seperator / old_seperator)[1] * old_clique[1, :]))
    print(new_seperator)
    print(new_clique,"\n")
    return new_clique, new_seperator

print('collect:-------------')
for index in range(1, len(cliques)):
    print(index, ':')
    cliques[index + 1], seperator[index + 1] = collect(cliques[index], cliques[index + 1])
    

    
    # distribute stage
def distribute(old_seperator, previous_clique, current_clique):
#     old_seperator = seperator[4]
#     previous_clique = cliques[4]
#     current_clique = cliques[3]
    old_clique = current_clique
    new_seperator = np.sum(previous_clique, axis=1)
    new_clique = np.column_stack(((new_seperator / old_seperator)[0] * old_clique[:, 0],
                               (new_seperator / old_seperator)[1] * old_clique[:, 1]))

    print(new_seperator)
    print(new_clique,"\n")
    return new_clique, new_seperator

print('distribute:-------------')
for index in range(len(cliques), 1, -1):
    print(index, ':')
    cliques[index - 1], seperator[index] = distribute(seperator[index], cliques[index], cliques[index - 1])


print('normalize:--------------')
for index in range(len(cliques)):
    cliques[index+1] = cliques[index + 1] / np.sum(cliques[index + 1])
    if index != 3:
        seperator[index+2] = np.sum(cliques[index+1], axis=0)

prob_1 = np.sum(cliques[1], axis=1)
prob_5 = np.sum(cliques[4], axis=0)


for i in range(1, len(cliques)+1):
    print('cliquex{}{}:\n{}'.format(i, i+1, cliques[i]))

print('')
print('p(x{}):{}'.format(1, prob_1))
for i in range(2, len(seperator)+2):
    print('p(x{}):{}'.format(i, seperator[i]))
print('p(x{}):{}'.format(5, prob_5))

initialize:--------
{1: array([[0.1, 0.7],
       [0.8, 0.3]]), 2: array([[0.5, 0.1],
       [0.1, 0.5]]), 3: array([[0.1, 0.5],
       [0.5, 0.1]]), 4: array([[0.9, 0.3],
       [0.1, 0.3]])}
collect:-------------
1 :
[0.9 1. ]
[[0.45 0.09]
 [0.1  0.5 ]] 

2 :
[0.55 0.59]
[[0.055 0.275]
 [0.295 0.059]] 

3 :
[0.35  0.334]
[[0.315  0.105 ]
 [0.0334 0.1002]] 

distribute:-------------
4 :
[0.42   0.1336]
[[0.066  0.11  ]
 [0.354  0.0236]] 

3 :
[0.176  0.3776]
[[0.144  0.0576]
 [0.032  0.32  ]] 

2 :
[0.2016 0.352 ]
[[0.0224 0.2464]
 [0.1792 0.1056]] 

normalize:--------------
cliquex12:
[[0.04046243 0.44508671]
 [0.32369942 0.19075145]]
cliquex23:
[[0.26011561 0.10404624]
 [0.05780347 0.57803468]]
cliquex34:
[[0.11921965 0.19869942]
 [0.63945087 0.04263006]]
cliquex45:
[[0.56900289 0.18966763]
 [0.06033237 0.18099711]]

p(x1):[0.48554913 0.51445087]
p(x2):[0.36416185 0.63583815]
p(x3):[0.31791908 0.68208092]
p(x4):[0.75867052 0.24132948]
p(x5):[0.62933526 0.37066474]
